// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphQLModel

import (
	"fmt"
	"io"
	"strconv"
)

type AtomKPINode interface {
	GetID() uint32
	GetParentNodeID() *uint32
	GetNodeType() KPINodeType
	GetSdParameterID() uint32
	GetSdParameterSpecification() string
}

type KPINode interface {
	GetID() uint32
	GetParentNodeID() *uint32
	GetNodeType() KPINodeType
}

type APIKey struct {
	ID             uint32   `json:"id"`
	Label          string   `json:"label"`
	ExpiresAt      *string  `json:"expiresAt,omitempty"`
	Revoked        bool     `json:"revoked"`
	RateLimit      *uint32  `json:"rateLimit,omitempty"`
	LastUsedAt     *string  `json:"lastUsedAt,omitempty"`
	Permissions    []string `json:"permissions"`
	IPRestrictions []string `json:"ipRestrictions"`
}

type APIKeyInput struct {
	Label          *string  `json:"label,omitempty"`
	ExpiresAt      *string  `json:"expiresAt,omitempty"`
	Revoked        *bool    `json:"revoked,omitempty"`
	RateLimit      *uint32  `json:"rateLimit,omitempty"`
	Permissions    []string `json:"permissions,omitempty"`
	IPRestrictions []string `json:"ipRestrictions,omitempty"`
}

type AssignRoleInput struct {
	UserID uint32 `json:"userID"`
	RoleID uint32 `json:"roleID"`
}

type BooleanEQAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	BooleanReferenceValue    bool        `json:"booleanReferenceValue"`
}

func (BooleanEQAtomKPINode) IsKPINode()                    {}
func (this BooleanEQAtomKPINode) GetID() uint32            { return this.ID }
func (this BooleanEQAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this BooleanEQAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (BooleanEQAtomKPINode) IsAtomKPINode() {}

func (this BooleanEQAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this BooleanEQAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type BooleanExistsAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
}

func (BooleanExistsAtomKPINode) IsKPINode()                    {}
func (this BooleanExistsAtomKPINode) GetID() uint32            { return this.ID }
func (this BooleanExistsAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this BooleanExistsAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (BooleanExistsAtomKPINode) IsAtomKPINode() {}

func (this BooleanExistsAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this BooleanExistsAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type BooleanNEQAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	BooleanReferenceValue    bool        `json:"booleanReferenceValue"`
}

func (BooleanNEQAtomKPINode) IsKPINode()                    {}
func (this BooleanNEQAtomKPINode) GetID() uint32            { return this.ID }
func (this BooleanNEQAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this BooleanNEQAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (BooleanNEQAtomKPINode) IsAtomKPINode() {}

func (this BooleanNEQAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this BooleanNEQAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type BooleanNotExistsAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
}

func (BooleanNotExistsAtomKPINode) IsKPINode()                    {}
func (this BooleanNotExistsAtomKPINode) GetID() uint32            { return this.ID }
func (this BooleanNotExistsAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this BooleanNotExistsAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (BooleanNotExistsAtomKPINode) IsAtomKPINode() {}

func (this BooleanNotExistsAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this BooleanNotExistsAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type FilterNodeInput struct {
	Type     FilterNodeType    `json:"type"`
	Operator *LogicalOperator  `json:"operator,omitempty"`
	Not      *bool             `json:"not,omitempty"`
	Rules    []FilterNodeInput `json:"rules,omitempty"`
	Rule     *FilterRuleInput  `json:"rule,omitempty"`
}

type FilterRuleInput struct {
	Field     string           `json:"field"`
	Target    FilterTargetType `json:"target"`
	Operator  FilterOperator   `json:"operator"`
	Value     *string          `json:"value,omitempty"`
	ValueType FilterValueType  `json:"valueType"`
}

type InputData struct {
	Time       string  `json:"time"`
	DeviceID   string  `json:"deviceId"`
	DeviceType *string `json:"deviceType,omitempty"`
	Data       string  `json:"data"`
}

type KPIDefinition struct {
	ID                     uint32         `json:"id"`
	Label                  string         `json:"label"`
	SdTypeID               uint32         `json:"sdTypeID"`
	SdTypeSpecification    string         `json:"sdTypeSpecification"`
	UserIdentifier         string         `json:"userIdentifier"`
	Nodes                  []KPINode      `json:"nodes"`
	SdInstanceMode         SDInstanceMode `json:"sdInstanceMode"`
	SelectedSDInstanceUIDs []string       `json:"selectedSDInstanceUIDs"`
}

type KPIDefinitionInput struct {
	Label                  string         `json:"label"`
	SdTypeID               uint32         `json:"sdTypeID"`
	SdTypeSpecification    string         `json:"sdTypeSpecification"`
	UserIdentifier         string         `json:"userIdentifier"`
	Nodes                  []KPINodeInput `json:"nodes"`
	SdInstanceMode         SDInstanceMode `json:"sdInstanceMode"`
	SelectedSDInstanceUIDs []string       `json:"selectedSDInstanceUIDs"`
}

type KPIFulfillmentCheckResult struct {
	KpiDefinitionID uint32 `json:"kpiDefinitionID"`
	SdInstanceID    uint32 `json:"sdInstanceID"`
	Fulfilled       bool   `json:"fulfilled"`
}

type KPIFulfillmentCheckResultTuple struct {
	KpiFulfillmentCheckResults []KPIFulfillmentCheckResult `json:"kpiFulfillmentCheckResults"`
}

type KPINodeInput struct {
	Type                     KPINodeType           `json:"type"`
	ID                       uint32                `json:"id"`
	ParentNodeID             *uint32               `json:"parentNodeID,omitempty"`
	SdParameterID            *uint32               `json:"sdParameterID,omitempty"`
	SdParameterSpecification *string               `json:"sdParameterSpecification,omitempty"`
	StringReferenceValue     *string               `json:"stringReferenceValue,omitempty"`
	BooleanReferenceValue    *bool                 `json:"booleanReferenceValue,omitempty"`
	NumericReferenceValue    *float64              `json:"numericReferenceValue,omitempty"`
	LogicalOperationType     *LogicalOperationType `json:"logicalOperationType,omitempty"`
}

type LogicalOperationKPINode struct {
	ID           uint32               `json:"id"`
	ParentNodeID *uint32              `json:"parentNodeID,omitempty"`
	NodeType     KPINodeType          `json:"nodeType"`
	Type         LogicalOperationType `json:"type"`
}

func (LogicalOperationKPINode) IsKPINode()                    {}
func (this LogicalOperationKPINode) GetID() uint32            { return this.ID }
func (this LogicalOperationKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this LogicalOperationKPINode) GetNodeType() KPINodeType { return this.NodeType }

type Mutation struct {
}

type NumericEQAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	NumericReferenceValue    float64     `json:"numericReferenceValue"`
}

func (NumericEQAtomKPINode) IsKPINode()                    {}
func (this NumericEQAtomKPINode) GetID() uint32            { return this.ID }
func (this NumericEQAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this NumericEQAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (NumericEQAtomKPINode) IsAtomKPINode() {}

func (this NumericEQAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this NumericEQAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type NumericExistsAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
}

func (NumericExistsAtomKPINode) IsKPINode()                    {}
func (this NumericExistsAtomKPINode) GetID() uint32            { return this.ID }
func (this NumericExistsAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this NumericExistsAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (NumericExistsAtomKPINode) IsAtomKPINode() {}

func (this NumericExistsAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this NumericExistsAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type NumericGEQAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	NumericReferenceValue    float64     `json:"numericReferenceValue"`
}

func (NumericGEQAtomKPINode) IsKPINode()                    {}
func (this NumericGEQAtomKPINode) GetID() uint32            { return this.ID }
func (this NumericGEQAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this NumericGEQAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (NumericGEQAtomKPINode) IsAtomKPINode() {}

func (this NumericGEQAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this NumericGEQAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type NumericGTAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	NumericReferenceValue    float64     `json:"numericReferenceValue"`
}

func (NumericGTAtomKPINode) IsKPINode()                    {}
func (this NumericGTAtomKPINode) GetID() uint32            { return this.ID }
func (this NumericGTAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this NumericGTAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (NumericGTAtomKPINode) IsAtomKPINode() {}

func (this NumericGTAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this NumericGTAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type NumericLEQAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	NumericReferenceValue    float64     `json:"numericReferenceValue"`
}

func (NumericLEQAtomKPINode) IsKPINode()                    {}
func (this NumericLEQAtomKPINode) GetID() uint32            { return this.ID }
func (this NumericLEQAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this NumericLEQAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (NumericLEQAtomKPINode) IsAtomKPINode() {}

func (this NumericLEQAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this NumericLEQAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type NumericLTAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	NumericReferenceValue    float64     `json:"numericReferenceValue"`
}

func (NumericLTAtomKPINode) IsKPINode()                    {}
func (this NumericLTAtomKPINode) GetID() uint32            { return this.ID }
func (this NumericLTAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this NumericLTAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (NumericLTAtomKPINode) IsAtomKPINode() {}

func (this NumericLTAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this NumericLTAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type NumericNEQAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	NumericReferenceValue    float64     `json:"numericReferenceValue"`
}

func (NumericNEQAtomKPINode) IsKPINode()                    {}
func (this NumericNEQAtomKPINode) GetID() uint32            { return this.ID }
func (this NumericNEQAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this NumericNEQAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (NumericNEQAtomKPINode) IsAtomKPINode() {}

func (this NumericNEQAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this NumericNEQAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type NumericNotExistsAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
}

func (NumericNotExistsAtomKPINode) IsKPINode()                    {}
func (this NumericNotExistsAtomKPINode) GetID() uint32            { return this.ID }
func (this NumericNotExistsAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this NumericNotExistsAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (NumericNotExistsAtomKPINode) IsAtomKPINode() {}

func (this NumericNotExistsAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this NumericNotExistsAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type OutputData struct {
	Time       string  `json:"time"`
	DeviceID   string  `json:"deviceId"`
	DeviceType *string `json:"deviceType,omitempty"`
	Data       string  `json:"data"`
}

type Query struct {
}

type Role struct {
	ID          uint32   `json:"id"`
	Label       string   `json:"label"`
	Permissions []string `json:"permissions,omitempty"`
}

type SDInstance struct {
	ID              uint32 `json:"id"`
	UID             string `json:"uid"`
	Label           string `json:"label"`
	ConfirmedByUser bool   `json:"confirmedByUser"`
	UserIdentifier  string `json:"userIdentifier"`
	Type            SDType `json:"type"`
}

type SDInstanceGroup struct {
	ID             uint32   `json:"id"`
	Label          string   `json:"label"`
	UserIdentifier string   `json:"userIdentifier"`
	SdInstanceIDs  []uint32 `json:"sdInstanceIDs"`
}

type SDInstanceGroupInput struct {
	Label          string   `json:"label"`
	UserIdentifier string   `json:"userIdentifier"`
	SdInstanceIDs  []uint32 `json:"sdInstanceIDs"`
}

type SDInstanceUpdateInput struct {
	Label           *string `json:"label,omitempty"`
	UserIdentifier  *string `json:"userIdentifier,omitempty"`
	ConfirmedByUser *bool   `json:"confirmedByUser,omitempty"`
}

type SDParameter struct {
	ID         uint32          `json:"id"`
	Label      string          `json:"label"`
	Denotation string          `json:"denotation"`
	Type       SDParameterType `json:"type"`
	Role       SDParameterRole `json:"role"`
}

type SDParameterInput struct {
	Label      string          `json:"label"`
	Denotation string          `json:"denotation"`
	Type       SDParameterType `json:"type"`
	Role       SDParameterRole `json:"role"`
}

type SDType struct {
	ID         uint32        `json:"id"`
	Label      string        `json:"label"`
	Denotation string        `json:"denotation"`
	Parameters []SDParameter `json:"parameters"`
}

type SDTypeInput struct {
	Label      string             `json:"label"`
	Denotation string             `json:"denotation"`
	Parameters []SDParameterInput `json:"parameters"`
}

type SensorField struct {
	Key    string   `json:"key"`
	Values []string `json:"values"`
}

type SensorsWithFields struct {
	Sensors []SensorField `json:"sensors"`
}

type SimpleSensors struct {
	Sensors []string `json:"sensors"`
}

// Data used for querying the selected bucket
type StatisticsInput struct {
	// Start of the querying window
	From *string `json:"from,omitempty"`
	// End of the querying window
	To *string `json:"to,omitempty"`
	// Amount of minutes to aggregate by
	// For example if the queried range has 1 hour and aggregateMinutes is set to 10 the aggregation will result in 6 points
	AggregateMinutes *int `json:"aggregateMinutes,omitempty"`
	// Timezone override default UTC.
	// For more details why and how this affects queries see: https://www.influxdata.com/blog/time-zones-in-flux/.
	// In most cases you can ignore this and some edge aggregations can be influenced.
	// If you need a precise result or the aggregation uses high amount of minutes provide the target time zone.
	Timezone *string `json:"timezone,omitempty"`
	// Aggregation operator to use, if needed
	Operation *StatisticsOperation `json:"operation,omitempty"`
}

type StringEQAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	StringReferenceValue     string      `json:"stringReferenceValue"`
}

func (StringEQAtomKPINode) IsKPINode()                    {}
func (this StringEQAtomKPINode) GetID() uint32            { return this.ID }
func (this StringEQAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this StringEQAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (StringEQAtomKPINode) IsAtomKPINode() {}

func (this StringEQAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this StringEQAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type StringExistsAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
}

func (StringExistsAtomKPINode) IsKPINode()                    {}
func (this StringExistsAtomKPINode) GetID() uint32            { return this.ID }
func (this StringExistsAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this StringExistsAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (StringExistsAtomKPINode) IsAtomKPINode() {}

func (this StringExistsAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this StringExistsAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type StringNEQAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
	StringReferenceValue     string      `json:"stringReferenceValue"`
}

func (StringNEQAtomKPINode) IsKPINode()                    {}
func (this StringNEQAtomKPINode) GetID() uint32            { return this.ID }
func (this StringNEQAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this StringNEQAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (StringNEQAtomKPINode) IsAtomKPINode() {}

func (this StringNEQAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this StringNEQAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type StringNotExistsAtomKPINode struct {
	ID                       uint32      `json:"id"`
	ParentNodeID             *uint32     `json:"parentNodeID,omitempty"`
	NodeType                 KPINodeType `json:"nodeType"`
	SdParameterID            uint32      `json:"sdParameterID"`
	SdParameterSpecification string      `json:"sdParameterSpecification"`
}

func (StringNotExistsAtomKPINode) IsKPINode()                    {}
func (this StringNotExistsAtomKPINode) GetID() uint32            { return this.ID }
func (this StringNotExistsAtomKPINode) GetParentNodeID() *uint32 { return this.ParentNodeID }
func (this StringNotExistsAtomKPINode) GetNodeType() KPINodeType { return this.NodeType }

func (StringNotExistsAtomKPINode) IsAtomKPINode() {}

func (this StringNotExistsAtomKPINode) GetSdParameterID() uint32 { return this.SdParameterID }
func (this StringNotExistsAtomKPINode) GetSdParameterSpecification() string {
	return this.SdParameterSpecification
}

type Subscription struct {
}

type UserConfig struct {
	UserID uint32 `json:"userId"`
	Config string `json:"config"`
}

type UserConfigInput struct {
	Config string `json:"config"`
}

type KPINodeType string

const (
	KPINodeTypeStringEQAtom         KPINodeType = "StringEQAtom"
	KPINodeTypeStringNEQAtom        KPINodeType = "StringNEQAtom"
	KPINodeTypeStringExistsAtom     KPINodeType = "StringExistsAtom"
	KPINodeTypeStringNotExistsAtom  KPINodeType = "StringNotExistsAtom"
	KPINodeTypeBooleanEQAtom        KPINodeType = "BooleanEQAtom"
	KPINodeTypeBooleanNEQAtom       KPINodeType = "BooleanNEQAtom"
	KPINodeTypeBooleanExistsAtom    KPINodeType = "BooleanExistsAtom"
	KPINodeTypeBooleanNotExistsAtom KPINodeType = "BooleanNotExistsAtom"
	KPINodeTypeNumericEQAtom        KPINodeType = "NumericEQAtom"
	KPINodeTypeNumericNEQAtom       KPINodeType = "NumericNEQAtom"
	KPINodeTypeNumericGTAtom        KPINodeType = "NumericGTAtom"
	KPINodeTypeNumericGEQAtom       KPINodeType = "NumericGEQAtom"
	KPINodeTypeNumericLTAtom        KPINodeType = "NumericLTAtom"
	KPINodeTypeNumericLEQAtom       KPINodeType = "NumericLEQAtom"
	KPINodeTypeNumericExistsAtom    KPINodeType = "NumericExistsAtom"
	KPINodeTypeNumericNotExistsAtom KPINodeType = "NumericNotExistsAtom"
	KPINodeTypeLogicalOperation     KPINodeType = "LogicalOperation"
)

var AllKPINodeType = []KPINodeType{
	KPINodeTypeStringEQAtom,
	KPINodeTypeStringNEQAtom,
	KPINodeTypeStringExistsAtom,
	KPINodeTypeStringNotExistsAtom,
	KPINodeTypeBooleanEQAtom,
	KPINodeTypeBooleanNEQAtom,
	KPINodeTypeBooleanExistsAtom,
	KPINodeTypeBooleanNotExistsAtom,
	KPINodeTypeNumericEQAtom,
	KPINodeTypeNumericNEQAtom,
	KPINodeTypeNumericGTAtom,
	KPINodeTypeNumericGEQAtom,
	KPINodeTypeNumericLTAtom,
	KPINodeTypeNumericLEQAtom,
	KPINodeTypeNumericExistsAtom,
	KPINodeTypeNumericNotExistsAtom,
	KPINodeTypeLogicalOperation,
}

func (e KPINodeType) IsValid() bool {
	switch e {
	case KPINodeTypeStringEQAtom, KPINodeTypeStringNEQAtom, KPINodeTypeStringExistsAtom, KPINodeTypeStringNotExistsAtom, KPINodeTypeBooleanEQAtom, KPINodeTypeBooleanNEQAtom, KPINodeTypeBooleanExistsAtom, KPINodeTypeBooleanNotExistsAtom, KPINodeTypeNumericEQAtom, KPINodeTypeNumericNEQAtom, KPINodeTypeNumericGTAtom, KPINodeTypeNumericGEQAtom, KPINodeTypeNumericLTAtom, KPINodeTypeNumericLEQAtom, KPINodeTypeNumericExistsAtom, KPINodeTypeNumericNotExistsAtom, KPINodeTypeLogicalOperation:
		return true
	}
	return false
}

func (e KPINodeType) String() string {
	return string(e)
}

func (e *KPINodeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KPINodeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KPINodeType", str)
	}
	return nil
}

func (e KPINodeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type LogicalOperationType string

const (
	LogicalOperationTypeAnd LogicalOperationType = "AND"
	LogicalOperationTypeOr  LogicalOperationType = "OR"
	LogicalOperationTypeNor LogicalOperationType = "NOR"
	LogicalOperationTypeNot LogicalOperationType = "NOT"
)

var AllLogicalOperationType = []LogicalOperationType{
	LogicalOperationTypeAnd,
	LogicalOperationTypeOr,
	LogicalOperationTypeNor,
	LogicalOperationTypeNot,
}

func (e LogicalOperationType) IsValid() bool {
	switch e {
	case LogicalOperationTypeAnd, LogicalOperationTypeOr, LogicalOperationTypeNor, LogicalOperationTypeNot:
		return true
	}
	return false
}

func (e LogicalOperationType) String() string {
	return string(e)
}

func (e *LogicalOperationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogicalOperationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogicalOperationType", str)
	}
	return nil
}

func (e LogicalOperationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type LogicalOperator string

const (
	LogicalOperatorAnd LogicalOperator = "AND"
	LogicalOperatorOr  LogicalOperator = "OR"
	LogicalOperatorNot LogicalOperator = "NOT"
)

var AllLogicalOperator = []LogicalOperator{
	LogicalOperatorAnd,
	LogicalOperatorOr,
	LogicalOperatorNot,
}

func (e LogicalOperator) IsValid() bool {
	switch e {
	case LogicalOperatorAnd, LogicalOperatorOr, LogicalOperatorNot:
		return true
	}
	return false
}

func (e LogicalOperator) String() string {
	return string(e)
}

func (e *LogicalOperator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LogicalOperator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LogicalOperator", str)
	}
	return nil
}

func (e LogicalOperator) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ParameterType string

const (
	ParameterTypeBase  ParameterType = "BASE"
	ParameterTypeTag   ParameterType = "TAG"
	ParameterTypeField ParameterType = "FIELD"
)

var AllParameterType = []ParameterType{
	ParameterTypeBase,
	ParameterTypeTag,
	ParameterTypeField,
}

func (e ParameterType) IsValid() bool {
	switch e {
	case ParameterTypeBase, ParameterTypeTag, ParameterTypeField:
		return true
	}
	return false
}

func (e ParameterType) String() string {
	return string(e)
}

func (e *ParameterType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ParameterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ParameterType", str)
	}
	return nil
}

func (e ParameterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SDInstanceMode string

const (
	SDInstanceModeAll      SDInstanceMode = "ALL"
	SDInstanceModeSelected SDInstanceMode = "SELECTED"
)

var AllSDInstanceMode = []SDInstanceMode{
	SDInstanceModeAll,
	SDInstanceModeSelected,
}

func (e SDInstanceMode) IsValid() bool {
	switch e {
	case SDInstanceModeAll, SDInstanceModeSelected:
		return true
	}
	return false
}

func (e SDInstanceMode) String() string {
	return string(e)
}

func (e *SDInstanceMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SDInstanceMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SDInstanceMode", str)
	}
	return nil
}

func (e SDInstanceMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SDParameterRole string

const (
	SDParameterRoleField SDParameterRole = "FIELD"
	SDParameterRoleTag   SDParameterRole = "TAG"
)

var AllSDParameterRole = []SDParameterRole{
	SDParameterRoleField,
	SDParameterRoleTag,
}

func (e SDParameterRole) IsValid() bool {
	switch e {
	case SDParameterRoleField, SDParameterRoleTag:
		return true
	}
	return false
}

func (e SDParameterRole) String() string {
	return string(e)
}

func (e *SDParameterRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SDParameterRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SDParameterRole", str)
	}
	return nil
}

func (e SDParameterRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SDParameterType string

const (
	SDParameterTypeString  SDParameterType = "STRING"
	SDParameterTypeNumber  SDParameterType = "NUMBER"
	SDParameterTypeBoolean SDParameterType = "BOOLEAN"
)

var AllSDParameterType = []SDParameterType{
	SDParameterTypeString,
	SDParameterTypeNumber,
	SDParameterTypeBoolean,
}

func (e SDParameterType) IsValid() bool {
	switch e {
	case SDParameterTypeString, SDParameterTypeNumber, SDParameterTypeBoolean:
		return true
	}
	return false
}

func (e SDParameterType) String() string {
	return string(e)
}

func (e *SDParameterType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SDParameterType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SDParameterType", str)
	}
	return nil
}

func (e SDParameterType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type StatisticsOperation string

const (
	StatisticsOperationMean            StatisticsOperation = "mean"
	StatisticsOperationMin             StatisticsOperation = "min"
	StatisticsOperationMax             StatisticsOperation = "max"
	StatisticsOperationFirst           StatisticsOperation = "first"
	StatisticsOperationSum             StatisticsOperation = "sum"
	StatisticsOperationLast            StatisticsOperation = "last"
	StatisticsOperationNone            StatisticsOperation = "none"
	StatisticsOperationCount           StatisticsOperation = "count"
	StatisticsOperationIntegral        StatisticsOperation = "integral"
	StatisticsOperationMedian          StatisticsOperation = "median"
	StatisticsOperationMode            StatisticsOperation = "mode"
	StatisticsOperationQuantile        StatisticsOperation = "quantile"
	StatisticsOperationReduce          StatisticsOperation = "reduce"
	StatisticsOperationSkew            StatisticsOperation = "skew"
	StatisticsOperationSpread          StatisticsOperation = "spread"
	StatisticsOperationStddev          StatisticsOperation = "stddev"
	StatisticsOperationTimeweightedavg StatisticsOperation = "timeweightedavg"
)

var AllStatisticsOperation = []StatisticsOperation{
	StatisticsOperationMean,
	StatisticsOperationMin,
	StatisticsOperationMax,
	StatisticsOperationFirst,
	StatisticsOperationSum,
	StatisticsOperationLast,
	StatisticsOperationNone,
	StatisticsOperationCount,
	StatisticsOperationIntegral,
	StatisticsOperationMedian,
	StatisticsOperationMode,
	StatisticsOperationQuantile,
	StatisticsOperationReduce,
	StatisticsOperationSkew,
	StatisticsOperationSpread,
	StatisticsOperationStddev,
	StatisticsOperationTimeweightedavg,
}

func (e StatisticsOperation) IsValid() bool {
	switch e {
	case StatisticsOperationMean, StatisticsOperationMin, StatisticsOperationMax, StatisticsOperationFirst, StatisticsOperationSum, StatisticsOperationLast, StatisticsOperationNone, StatisticsOperationCount, StatisticsOperationIntegral, StatisticsOperationMedian, StatisticsOperationMode, StatisticsOperationQuantile, StatisticsOperationReduce, StatisticsOperationSkew, StatisticsOperationSpread, StatisticsOperationStddev, StatisticsOperationTimeweightedavg:
		return true
	}
	return false
}

func (e StatisticsOperation) String() string {
	return string(e)
}

func (e *StatisticsOperation) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StatisticsOperation(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StatisticsOperation", str)
	}
	return nil
}

func (e StatisticsOperation) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
