# @file apíKeys.graphql
# @brief GraphQL operace pro správu API klíčů, oprávnění a IP restrikcí.
#
# @author Vojtěch Hubáček
#
# @par Autorský podíl
# - Vojtěch Hubáček: návrh a implementace celé funkcionality souboru.
#
# @ingroup riot_frontend

query ApiKeys {
  apiKeys {
    id
    label
    revoked
    expiresAt
    permissions
    ipRestrictions
  }
}

mutation CreateApiKey($input: APIKeyInput!) {
  createAPIKey(input: $input)
}

mutation UpdateApiKey($id: ID!, $input: APIKeyInput!) {
  updateAPIKey(id: $id, input: $input)
}

mutation DeleteApiKey($id: ID!) {
  deleteAPIKey(id: $id)
}