# @file sdInstances.graphql
# @brief GraphQL dotazy a subscription pro sledované instance a raw datové body.
#
# @author Vojtěch Hubáček
#
# @par Autorský podíl
# - Vojtěch Hubáček: návrh a implementace celé funkcionality souboru.
#
# @ingroup riot_frontend

query SdInstances {
  sdInstances {
    id
    uid
    label
  }
}

query SdInstancesByType($id: ID!) {
  sdInstancesByType(id: $id) {
    id
    uid
    label
    type {
      id
    }
  }
}

query SdInstancesByKpiDefinition($id: ID!) {
  sdInstancesByKpiDefinition(id: $id) {
    id
    uid
    label
  }
}

query RawDataPoint($id: ID!) {
  rawDataPoint(id: $id) {
    sdInstanceID
    payload
    eventTime
  }
}

subscription OnRawDataPointArrived($filter: RawDataPointArrivedFilter) {
  onRawDataPointArrived(filter: $filter) {
    sdTypeID
    sdInstanceID
    payload
    eventTime
  }
}

query SdInstance($id: ID!) {
  sdInstance(id: $id) {
    id
    uid
    label
    confirmedByUser
    userIdentifier
    type {
      id
      uid
      label
      parameters {
        id
        label
        denotation
        type
        role
      }
    }
  }
}