# @file timeSeries.graphql
# @brief GraphQL operace a subscription pro historii, agregace a exporty časových řad.
#
# @author Vojtěch Hubáček
#
# @par Autorský podíl
# - Vojtěch Hubáček: návrh a implementace celé funkcionality souboru.
#
# @ingroup riot_frontend

query TimeSeriesRead($request: TimeSeriesReadInput!) {
  timeSeriesRead(request: $request) {
    base
    data {
      time
      tags
      data
    }
    parameters {
      denotation
      label
      role
    }
    hasMoreBatches
    hasMoreData
    nextCursor {
      time
      sdInstanceUID
      kpiDefinitionUID
    }
    error
  }
}

mutation StartTimeSeriesExport($input: TimeSeriesReadInput!) {
  startTimeSeriesExport(input: $input) {
    uid
    status
    downloadUrl
    createdAt
    expiresAt
    error
  }
}

mutation CancelTimeSeriesExport($uid: String!) {
  cancelTimeSeriesExport(uid: $uid) {
    uid
    status
    downloadUrl
    createdAt
    expiresAt
    error
  }
}

query TimeSeriesExport($uid: String!) {
  timeSeriesExport(uid: $uid) {
    uid
    status
    downloadUrl
    createdAt
    expiresAt
    error
  }
}

subscription OnTimeSeriesExportUpdated($filter: TimeSeriesExportFilter!) {
  onTimeSeriesExportUpdated(filter: $filter) {
    uid
    status
    downloadUrl
    createdAt
    expiresAt
    error
  }
}

query TimeSeriesReadAggregateKpi($request: TimeSeriesReadAggregateKPIInput!) {
  timeSeriesReadAggregateKPI(request: $request) {
    parameters {
      denotation
      label
      role
    }
    base
    data {
      time
      tags
      data
    }
    hasMoreBatches
    hasMoreData
    nextCursor {
      time
      sdInstanceUID
      kpiDefinitionUID
    }
    error
  }
}
